# Importar librerias

In [1]:
import janitor
import matplotlib.pyplot as plt
import missingno as msno
import numpy as np
import pandas as pd
import pyreadr
import seaborn

import warnings
warnings.filterwarnings('ignore')

# Extensión de pandas

In [2]:
%run pandas-missing-extension.ipynb

# Datos nulos

## Diferentes formas que se ven los nulos

### Como se ven datos nulos en Python

In [3]:
print(None or True,
      None or False,
      None or 0,
      None or 1,
      None or [],
      None or [1, 2, 3],
      None or '',
      None or 'Hello',
      None or {},
      None or {'a': 1, 'b': 2},
      type(None),
      sep = '\n'
)

True
False
0
1
[]
[1, 2, 3]

Hello
{}
{'a': 1, 'b': 2}
<class 'NoneType'>

### Como se manejan datos nulos en Numpy

In [4]:
print(np.nan or True,
      np.nan == np.nan,
      type(np.nan),
      sep = '\n'
)

nan
False
<class 'float'>

### Como se manejan los datos nulos en Pandas

In [5]:
prueba_faltante = pd.DataFrame.from_dict(data = dict(
  x = [0, 1, np.nan, np.nan, None],
  y = [0, 1, pd.NA, np.nan, None]
))

prueba_faltante

     x     y
0  0.0     0
1  1.0     1
2  NaN  <NA>
3  NaN   NaN
4  NaN  None

## Metodos detectar datos nulos

### Detectar datos nulos desde un Dataframe

Metodo .isna() de pandas devuelve un DataFrame de True/False dependiendo si identifica en la entrada un registro nulo

In [6]:
prueba_faltante.isna()

       x      y
0  False  False
1  False  False
2   True   True
3   True   True
4   True   True

In [14]:
print("Cantidad de valores Nulos", prueba_faltante.missing.number_missing())
print("Cantidad de valores NO Nulos", prueba_faltante.missing.number_complete())

Cantidad de valores Nulos 6
Cantidad de valores NO Nulos 4

### Detectar datos nulos en Series de tiempo

In [7]:
pd.Series([1, np.nan])

0    1.0
1    NaN
dtype: float64

In [8]:
pd.Series([pd.to_datetime('2022-01-01'), np.nan])

0   2022-01-01
1          NaT
dtype: datetime64[us]

## Extensión de Pandas de Datos Nulos

### **iloc**
Llena con el valor que se de en los valores que se pasan.
[desde:hasta+1, index columna]

In [10]:
df = pd.DataFrame.from_dict(data = {"a": list('asdfasdfas'), "b": range(0,10)})
df.iloc[2:5, 0] = None
df.iloc[6:7, 1] = None
df

     a    b
0    a  0.0
1    s  1.0
2  NaN  2.0
3  NaN  3.0
4  NaN  4.0
5    s  5.0
6    d  NaN
7    f  7.0
8    a  8.0
9    s  9.0

In [13]:
print("Cantidad de valores Nulos", df.missing.number_missing())
print("Cantidad de valores NO Nulos", df.missing.number_complete())

Cantidad de valores Nulos 4
Cantidad de valores NO Nulos 16